### ISSUE TITLE
fix demo/docs url pls

### ISSUE THREAD

**Issue by axe312ger** [wix-incubator/kampos#20]
hey, looks like this repo got moved.

Can you please adjust the paths to the demo/docs? https://wix-incubator.github.io/kampos/

**Comment by ydaniv** [comment]
hey @axe312ger, thanks for noting this! I'll fix right away

**Comment by axe312ger** [comment]
Great, thanks!

**Comment by axe312ger** [comment]
Did you maybe forget to change in the repository about section? 🙈 
<img width="329" alt="Screenshot 2023-03-27 at 15 01 44" src="https://user-images.githubusercontent.com/1737026/227946524-7f279d67-6d3a-45fb-8660-fb5d952c68bf.png">
